# Project information
site_name: DeterminingTheFuture
site_url: https://vgrigoryevsky.github.io/determiningthefuture
site_author: Valentin Grigoryevsky
site_description: >-
  Explore theories, methodologies, solutions, and sci-fi concepts 
  for forecasting the future, with a focus on strategic modelling.

# Copyright
copyright: Copyright &copy; 2024 DeterminingTheFuture

# Configuration
theme:
  name: material
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    # - content.code.select
    # - content.footnote.tooltips
    # - content.tabs.link
    - content.tooltips
    # - header.autohide
    # - navigation.expand
    # - navigation.footer
    - navigation.indexes
    # - navigation.instant
    # - navigation.instant.prefetch
    # - navigation.instant.progress
    # - navigation.prune
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    # - toc.integrate
  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - media: "(prefers-color-scheme: light)"
      scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  font:
    h: Fira Code
    text:  Fira Code
    code: Source Code Pro
  favicon: assets/images/favicon.ico
  logo: assets/images/logo.svg


extra_css:
  - assets/stylesheets/extra.css

plugins:
  - blog:
      post_date_format: full
      archive_name: Posting date
      archive_date_format: MMMM yyyy
      archive_url_date_format: yyyy/MM
      archive_url_format: "{date}"
      categories_url_format: "{slug}"
      categories_allowed:
        - 0. Announcements
        - 0. Trending
        - 1. Theories
        - 2. Methodologies
        - 3. Solutions
        - 4. Culture
        - 5. Concepts
        - 6. Events
        - 7. Social Media
  - search:
      separator: '[\s\u200b\-_,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - social

# Additional configuration
extra:
  status:
    new: Recently added
    deprecated: Deprecated
  analytics:
    provider: google
    property: G-D5VX16XM87
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/vgrigoryevsky/determiningthefuture
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/determiningthefuture
    - icon: fontawesome/brands/threads
      link: https://www.threads.net/@determiningthefuture
    - icon: fontawesome/brands/x-twitter
      link: https://x.com/determthefuture
    - icon: fontawesome/brands/telegram
      link: https://t.me/determiningthefuture
  generator: false


# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      auto_append:
        - includes/mkdocs.md
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# not_in_nav: |


# Page tree
nav:
  - Pathways to the Future:
      - blog/index.md
  - Echo of the Future:
    - echo/index.md
  - References:
      - references/index.md
      - Forecasts:
          - references/forecasts/index.md
      - Theories:
        - references/theories/index.md
      - Methodologies:
          - references/methodologies/index.md
      - Solutions:
          - references/solutions/index.md
      - Culture:
          - references/culture/index.md
      - Events:
          - references/events/index.md
      - Social Media:
          - references/social-media/index.md
  - About:
    - index.md
    - Team: about/team.md
    - Contacts: about/contacts.md
    - FAQ:
      - about/faq/index.md
    - Contributing:
      - about/contributing/index.md
      - Asking a question: about/contributing/discussions.md
      - Reporting an issue: about/contributing/reporting-an-issue.md
    - Legal:
      - about/legal/LICENSE.md
      - ICLA: about/legal/ICLA.md
      - Credits: about/legal/credits.md
