# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json
site_name: Determining The Future
site_url: https://vgrigoryevsky.github.io/determiningthefuture

#repo_url: https://github.com/vgrigoryevsky/determiningthefuture

theme:
  name: material
  logo: assets/images/logo.svg
  favicon: assets/images/favicon.ico
  font:
    h:
      Monaco
    text:
      Monaco
    code:
      Consolas
  features:
    ## mkdocs-material language switcher contextual link is not compatible with theme.features = navigation.instant
    #- navigation.instant
    - navigation.path
#    - navigation.instant.prefetch
#    - navigation.instant.progress
    - navigation.indexes
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.sections
    - toc.follow
    - search.suggest
    - search.highlight
    - search.share
  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - media: "(prefers-color-scheme: light)"
      scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode


extra_css:
  - assets/stylesheets/extra.css

plugins:
  - i18n:
      languages:
        - locale: en
          name: English
          build: true
          default: true
          nav_translations:
            home: Latest updates
            echo: Echo of the Future
            ways: Ways to the Future
            methodologies: Methods & Methodologies
            solutions: Solutions
            literature: Literature
            culture: Culture
            refs: References
            about: About
            faq: FAQ
            contribute: Contributing
            issues: Report Issues
            lic: License
            icla: ICLA
        - locale: ru
          name: Russian
          build: true
          nav_translations:
            home: Последние обновления
            echo: Эхо будущего
            ways: Пути к будущему
            methodologies: Методы и метододологии
            solutions: Решения
            literature: Литература
            culture: Культура
            refs: Ссылки
            about: О проекте
            faq: Частые вопросы
            contribute: Присоединиться
            issues: Сообщить о проблеме
            lic: Лицензия на контент
            icla: ICLA
      reconfigure_search: true
      # material_alternate: true
  - search
  - blogging:
      dirs:
        - pages/ways-methodologies-review/blog
        - pages/ways-solutions-review/blog
        - pages/ways-literature-review/blog
        - pages/ways-culture-review/blog
      features:
        tags: { }

nav:
  - home: index.md
  - echo: pages/echo-of-the-future/TODO.md
  - ways:
      - methodologies:
          - description: pages/ways-methodologies-review/TODO.md
          - test: pages/ways-methodologies-review/blog/2024-08-13_00-13_Test-review-1.md
      - solutions: pages/ways-solutions-review/TODO.md
      - literature: pages/ways-literature-review/TODO.md
      - culture: pages/ways-culture-review/TODO.md
  - refs:
      - methodologies: pages/refs-methodologies-list/TODO.md
      - solutions: pages/refs-solutions-list/TODO.md
      - literature: pages/refs-literature-list/TODO.md
      - culture: pages/refs-culture-list/TODO.md
  - about:
      - faq: pages/faq/faq.md
      - issues: pages/issues/issues.md
      - contribute: pages/contributing/contributing.md
      - lic: pages/license/LICENSE.md
      - icla: pages/icla/ICLA.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/vgrigoryevsky/determiningthefuture
    - icon: fontawesome/brands/telegram
      link: https://t.me/your-handle
  generator: false
  manifest: false

copyright: © 2024 DeterminingTheFuture. All rights reserved.

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - attr_list
  - md_in_html
  - footnotes
  - tables
  - toc:
      permalink: true