authors:
  vgrigoryevsky:
    name: Valentin Grigoryevsky
    description: Founder
    avatar: assets/images/sa_icon.png
  kaan:
    name: Kaan
    description: Founder
    avatar: https://static.vecteezy.com/system/resources/previews/002/002/253/large_2x/beautiful-woman-wearing-sunglasses-avatar-character-icon-free-vector.jpg